name: Spleef
version: '0.1.0'
main: me.jdcomputers.src.Spleef
api-version: '1.21'
commands:
  spleef:
    description: The default spleef command
permissions:
  spleef:
    description: Main command
  spleef.arena:
    description: The base arena command
  spleef.arena.create:
    description: Allow users to create arenas
  spleef.arena.delete:
    description: Allow users to delete arenas
  spleef.arena.edit:
    description: Allow and teleport users to edit arenas
  spleef.arena.list:
    description: Allow users to see the list of arenas
  spleef.arena.spawn:
    description: Allow users to set the spawn of arenas
  spleef.config:
    description: Allow users to set config options through commands
  spleef.lobby:
    description: The base lobby command
  spleef.lobby.set:
    description: Allow users to set the location of the lobby
  spleef.lobby.teleport:
    description: Allow users to teleport to the lobby in gamemode creative
  spleef.*:
    description: Give access to all spleef commands
  spleef.arena.*:
    description: Give access to all arena commands
  spleef.lobby.*:
    description: Give access to all lobby commands